# -*- coding: utf-8 -*-

"""Pure python implementation of Peter Jaeckel's LetsBeRational."""

from py_lets_be_quickly_rational.lets_be_rational import black
from py_lets_be_quickly_rational.lets_be_rational import normalised_black
from py_lets_be_quickly_rational.lets_be_rational import normalised_black_call
from py_lets_be_quickly_rational.lets_be_rational import implied_volatility_from_a_transformed_rational_guess
from py_lets_be_quickly_rational.lets_be_rational import implied_volatility_from_a_transformed_rational_guess_with_limited_iterations
from py_lets_be_quickly_rational.lets_be_rational import normalised_implied_volatility_from_a_transformed_rational_guess
from py_lets_be_quickly_rational.lets_be_rational import normalised_implied_volatility_from_a_transformed_rational_guess_with_limited_iterations
from py_lets_be_quickly_rational.lets_be_rational import normalised_vega
from py_lets_be_quickly_rational.normaldistribution import norm_cdf
from py_lets_be_quickly_rational.exceptions import VolatilityValueException, BelowIntrinsicException, AboveMaximumException
